version: "3"

services:

  restaurant-application:
    container_name: "restaurant-backend"
    image: restaurant-java-server
    ports:
      - "8080:8080"
    networks:
      - restaurant-app-network
    environment:
      - DB_USER=postgres
      - DB_PASS=root123
      - EMAIL_USERNAME=restaurant.manage004@gmail.com
      - EMAIL_PASS=jgiqmhbnpuztcxlb
      - DB_PATH=jdbc:postgresql://134.122.65.76:5432/restaurant_db
      - MINIO_URL=http://134.122.65.76:9000
      - MINIO_USER=admin
      - MINIO_PASSWORD=restaurant@!2024

networks:
    restaurant-app-network:
      driver: bridge