version: "3"

services:
  restaurant-database:
    container_name: "restaurant-database"
    image: postgres:16
    ports:
      - "5432:5432"
    networks:
      - restaurant-app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=restaurant_db


  restaurant-application:
    container_name: "restaurant-backend"
#    image: restaurant-app
    ports:
      - "8080:8080"
    networks:
      - restaurant-app-network
    environment:
      - DB_USER=postgres
      - DB_PASS=root123
      - EMAIL_USERNAME=restaurant.manage004@gmail.com
      - EMAIL_PASS=jgiqmhbnpuztcxlb
      - DB_PATH=jdbc:postgresql://restaurant-database:5432/restaurant_db
    depends_on:
      - restaurant-database
#    command: ["./wait-for-it.sh", "restaurant-database:5432", "--", "java", "-jar", "restaurant-management-0.0.1-SNAPSHOT.jar"]


networks:
    restaurant-app-network:
      driver: bridge