name: Deploy Spring Boot App with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew  # Add this step to make the gradlew script executable

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Clean Spring Boot App
        run: ./gradlew clean

      - name: Build Spring Boot App
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image (No Cache)
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/restaurant-api:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-api:${{ github.sha }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy on Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            
            # Stop
            docker stop restaurant-java-server
            docker image remove ${{ secrets.DOCKER_USERNAME}}/restaurant-api
            docker image remove restaurant-java-server         
          
            # Start New image
            docker pull ${{ secrets.DOCKER_USERNAME }}/restaurant-api
            docker tag ${{ secrets.DOCKER_USERNAME }}/restaurant-api restaurant-java-server
          
            docker-compose -f ${{ secrets.DOCKER_COMPOSE_PATH }} up -d
          EOF
